general.import = ["~/programming/dotfiles/carbonfox.toml"]

[font]
size = 14.0
offset.y = 2

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-l", "-c", "zellij"]

[window]
option_as_alt = "OnlyLeft"
